image: golang:1.19-buster

before_script:
  - echo ':before_script'
  - cat /etc/os-release
  - echo 'end : before_script'

stages:
  - test 
  - build 
  - quality_check 
  - deploy 


test-backend:
  stage: test 
  script: 
    - CGO_ENABLED=O go test ./... -coverprofile=coverage-report.out
    -  go tool cover -html=coverage-report.out -o coverage-report.html
    -  go tool cover -func=coverage-report.out
artifacts:
  paths:
    - coverage-report.html
  expire_in: 1 days 
coverage: "/\\(statements\\)\\s+\\d+.?\\d+%/"

build-backend:
  stage: build 
  script: 
    - go build -o bin/cra-generator -v .
  artifacts:
    paths:
      - bin/cra-generator
    expire_in: 1 days 

sast:
  stage: quality_check
  before_script:
    -echo 'Static Application Security Testing (SAST) - from source code'
  timeout: 10m
include:
  - template: SAST.ci.yml

pages:
  stage: deploy 
  script:
    - echo 'Cleaning old pages'
    - rm -rf public 
    - ls -la 
    - ls -la ./public

  artifacts: 
    paths:
      - public 
    expire_in: 30 days 
  only:
    - master 
    - develop     

