apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporalioui:2.10.1
spec:
  replicas: 3
  selector:
    matchLabels:
      name: temporalioui:2.10.1
  template:
    metadata:
      labels:
        name: temporalioui:2.10.1
  spec:
    containers:
      - name: static-site
        image:  teejoshua/temporalioui:2.10.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080s